### ISSUE TITLE
Eclipse

### ISSUE THREAD

**Issue by arcticio** [mgreter/astro.js#2]
Don't know where and how to put it, so straight and simple:

Will this library help me to simulate the eclipse next month over a THREE.js sphere with a unit radius?

**Comment by mgreter** [comment]
If you have current enough kepler elements of the moon and earth you can calculate exact enough cartesian coordinates with this library. With that you could probably do what you want. To get  those Kepler elements you may use  http://github.com/mgreter/ephem.js  (vsop for earth and elp for the moon).

Basically seems to be something i did at http://ocbnet.ch/solsys-preview-15 with the mentioned libs.

**Comment by mgreter** [comment]
Forgot to mention that you'll also need accurate rotation model for earths equatorial reference frame (eg. https://github.com/mgreter/sofa.js/blob/develop/docs/iau.era00.md). For eclipses in the future you'd also need a correct precession and nutation model.

**Comment by mgreter** [comment]
Here a link to the 2017 solar eclipse in my solar system explorer: http://ocbnet.ch/solsys-preview-15/three-app-build/demo/solsys.html?stars=1#inert=earth&fov=65&pos.x=-0.00006312800500718664&pos.y=0.00003239728874253463&pos.z=0.00004241558727156442&tgt.x=0&tgt.y=0&tgt.z=0&jd=2457987.268521&speed=0.0002777777777777778
